version: '3'
services:
  # nextjs-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres-db

  postgres-db:
    build:
      context: ./postgres
      restart: always
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
